/* Test helper (slice S3): the T1 group tier, every subgroup of Sym(n) for n <= 4 (1, 1, 2, 6
 * and 30 subgroups), each with the greedy generating sequence of review_checks.run_v2
 * (repeatedly add the least element, as an image array, not yet generated).  Elements of
 * Sym(n) are numbered in lexicographic order of their image arrays, so "least" is "lowest
 * index".  Groups are bit masks over those indices (n! <= 24). */
#ifndef CANON_TESTS_T1_GROUPS_H
#define CANON_TESTS_T1_GROUPS_H

#include <stdint.h>
#include <string.h>

#define T1_MAX_GROUPS 30u

typedef struct t1_sym {
    uint32_t n, count;          /* count = n! */
    uint32_t elem[24][4];       /* lexicographic order */
    uint32_t mul[24][24];       /* index of elem[i] elem[j] (elem[i] acts first, spec 3) */
} t1_sym;

typedef struct t1_group {
    uint32_t mask;              /* members of Sym(n) */
    uint32_t order;
    uint32_t gen_count;
    uint32_t gens[24 * 4];      /* greedy generators, flat image arrays */
} t1_group;

static void t1_sym_init(t1_sym *s, uint32_t n)
{
    s->n = n;
    s->count = 0;
    /* lexicographic enumeration of image arrays */
    uint32_t a[4] = {0, 1, 2, 3};
    for (;;) {
        memcpy(s->elem[s->count++], a, sizeof a);
        if (n < 2) {
            break;
        }
        int i = (int)n - 2;
        while (i >= 0 && a[i] > a[i + 1]) {
            --i;
        }
        if (i < 0) {
            break;
        }
        int j = (int)n - 1;
        while (a[j] < a[i]) {
            --j;
        }
        uint32_t t = a[i];
        a[i] = a[j];
        a[j] = t;
        for (int l = i + 1, r = (int)n - 1; l < r; ++l, --r) {
            t = a[l];
            a[l] = a[r];
            a[r] = t;
        }
    }
    for (uint32_t i = 0; i < s->count; ++i) {
        for (uint32_t j = 0; j < s->count; ++j) {
            uint32_t p[4] = {0, 0, 0, 0};
            for (uint32_t v = 0; v < n; ++v) {
                p[v] = s->elem[j][s->elem[i][v]]; /* (pq)[v] = q[p[v]] */
            }
            for (uint32_t k = 0; k < s->count; ++k) {
                if (n == 0 || memcmp(p, s->elem[k], n * sizeof *p) == 0) {
                    s->mul[i][j] = k;
                    break;
                }
            }
        }
    }
}

/* The subgroup generated by the elements in `mask` (finite: products suffice). */
static uint32_t t1_closure(const t1_sym *s, uint32_t mask)
{
    uint32_t g = mask | 1u; /* index 0 is the identity */
    for (;;) {
        uint32_t next = g;
        for (uint32_t i = 0; i < s->count; ++i) {
            for (uint32_t j = 0; j < s->count; ++j) {
                if ((g >> i & 1u) && (mask >> j & 1u)) {
                    next |= 1u << s->mul[i][j];
                }
            }
        }
        if (next == g) {
            return g;
        }
        g = next;
    }
}

static uint32_t t1_popcount(uint32_t m)
{
    uint32_t c = 0;
    for (; m != 0; m &= m - 1) {
        ++c;
    }
    return c;
}

/* All subgroups of Sym(n), each with its greedy generators; returns the count. */
static uint32_t t1_subgroups(const t1_sym *s, t1_group *out)
{
    uint32_t count = 0;
    out[count++].mask = 1u;
    for (uint32_t k = 0; k < count; ++k) {
        for (uint32_t e = 0; e < s->count; ++e) {
            uint32_t m = t1_closure(s, out[k].mask | 1u << e);
            uint32_t seen = 0;
            for (uint32_t l = 0; l < count; ++l) {
                seen |= out[l].mask == m;
            }
            if (!seen && count < T1_MAX_GROUPS) {
                out[count++].mask = m;
            }
        }
    }
    for (uint32_t k = 0; k < count; ++k) {
        t1_group *g = &out[k];
        g->order = t1_popcount(g->mask);
        g->gen_count = 0;
        uint32_t chosen = 0, known = 1u;
        while (known != g->mask) {
            uint32_t e = 0;
            while (!((g->mask & ~known) >> e & 1u)) {
                ++e;
            }
            chosen |= 1u << e;
            memcpy(g->gens + g->gen_count * s->n, s->elem[e], s->n * sizeof(uint32_t));
            g->gen_count++;
            known = t1_closure(s, chosen);
        }
    }
    return count;
}

#endif /* CANON_TESTS_T1_GROUPS_H */
