/* Unit tests for the explicit group backend (src/bsgs/explicit.c; spec sections 7.1, 7.2, 9). */
#include <stdatomic.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "bsgs/explicit.h"
#include "check.h"

static canon_group *make(uint32_t n, const uint32_t *gens, size_t count, uint64_t cap)
{
    canon_group *g = NULL;
    canon_status st = canon_group_explicit_create(n, gens, count, cap, &g);
    CHECK(st == CANON_COMPLETE);
    CHECK(g != NULL);
    return g;
}

/* spec 9.1 membership through the ops (S3: contains reports allocation failure) */
static bool in(const canon_group *g, const uint32_t *p)
{
    bool r = false;
    CHECK(g->ops->contains(g, p, &r) == CANON_COMPLETE);
    return r;
}

static void drop(canon_group *g)
{
    canon_group_release(g); /* public release; the handle came from canon_group_alloc */
}

static int eq(const uint32_t *a, const uint32_t *b, uint32_t n)
{
    return n == 0 || memcmp(a, b, n * sizeof *a) == 0;
}

/* Sym(n) generated by the transposition (0 1) and the n-cycle v -> v+1 mod n. */
static canon_group *sym(uint32_t n, uint64_t cap, canon_status *st)
{
    uint32_t gens[2 * 8];
    for (uint32_t v = 0; v < n; ++v) {
        gens[v] = v;
        gens[n + v] = (v + 1) % n;
    }
    if (n >= 2) {
        gens[0] = 1;
        gens[1] = 0;
    }
    canon_group *g = NULL;
    *st = canon_group_explicit_create(n, gens, 2, cap, &g);
    return g;
}

int main(void)
{
    /* |Sym(n)| = n! for n <= 5. */
    const uint64_t fact[6] = {1, 1, 2, 6, 24, 120};
    for (uint32_t n = 0; n <= 5; ++n) {
        canon_status st;
        canon_group *g = sym(n, 1000, &st);
        CHECK(st == CANON_COMPLETE);
        if (g != NULL) {
            CHECK(g->ops->order(g) == fact[n]);
            CHECK(g->degree == n);
        }
        drop(g);
    }
    /* Capacity refusal: checked before growth, so exactly |G| is admitted. */
    {
        canon_status st;
        canon_group *g = sym(4, 23, &st);
        CHECK(st == CANON_CAPACITY_LIMIT && g == NULL);
        g = sym(4, 24, &st);
        CHECK(st == CANON_COMPLETE && g != NULL);
        drop(g);
        g = NULL;
        CHECK(canon_group_explicit_create(2, NULL, 0, 0, &g) == CANON_CAPACITY_LIMIT);
        CHECK(g == NULL);
    }
    /* Invalid generators: not a bijection, out of range. */
    {
        const uint32_t bad1[3] = {0, 0, 2}, bad2[3] = {0, 1, 3};
        canon_group *g = NULL;
        CHECK(canon_group_explicit_create(3, bad1, 1, 100, &g) == CANON_INVALID_INPUT);
        CHECK(g == NULL);
        CHECK(canon_group_explicit_create(3, bad2, 1, 100, &g) == CANON_INVALID_INPUT);
        CHECK(g == NULL);
    }
    /* |C_3| = 3, membership. */
    {
        const uint32_t c3[3] = {1, 2, 0};
        canon_group *g = make(3, c3, 1, 100);
        CHECK(g->ops->order(g) == 3);
        const uint32_t id[3] = {0, 1, 2}, r2[3] = {2, 0, 1}, tr[3] = {1, 0, 2};
        CHECK(in(g, id));
        CHECK(in(g, c3));
        CHECK(in(g, r2));
        CHECK(!in(g, tr));
        /* S3 review item 8: the explicit backend admits a descriptor iff |G| <= max_group_order */
        canon_capacity cap = {0, 3, 0, 0, 0, 0, 0, 0};
        CHECK(g->ops->admits(g, &cap) == CANON_COMPLETE);
        cap.max_group_order = 2;
        CHECK(g->ops->admits(g, &cap) == CANON_CAPACITY_LIMIT);
        /* tuple_min, hand computed: L=(1): images g[1] are 1, 2, 0, so M=(0), t=[2,0,1];
         * G_M trivial, orbits {0},{1},{2}. */
        uint32_t t[3], orb[3];
        const uint32_t L1[1] = {1};
        CHECK(g->ops->tuple_min(g, L1, 1, t, orb) == CANON_COMPLETE);
        CHECK(eq(t, r2, 3));
        CHECK(orb[0] == 0 && orb[1] == 1 && orb[2] == 2);
        /* Out-of-range list entry. */
        const uint32_t Lbad[1] = {3};
        CHECK(g->ops->tuple_min(g, Lbad, 1, t, orb) == CANON_INVALID_INPUT);
        drop(g);
    }
    /* Sym(3), L=(2): least image (0); elements with g[2]=0 are [1,2,0] and [2,1,0]; least is
     * [1,2,0].  G_M = Stab(0) = {id, (1 2)}: orbits {0},{1,2} -> ids [0,1,1]. */
    {
        canon_status st;
        canon_group *g = sym(3, 100, &st);
        uint32_t t[3], orb[3];
        const uint32_t L[1] = {2}, want[3] = {1, 2, 0};
        CHECK(g->ops->tuple_min(g, L, 1, t, orb) == CANON_COMPLETE);
        CHECK(eq(t, want, 3));
        CHECK(orb[0] == 0 && orb[1] == 1 && orb[2] == 1);
        /* Full list L=(2,0,1): unique t with t[2]=0, t[0]=1, t[1]=2 -> [1,2,0]; no orbits. */
        const uint32_t Lf[3] = {2, 0, 1};
        CHECK(g->ops->tuple_min(g, Lf, 3, t, NULL) == CANON_COMPLETE);
        CHECK(eq(t, want, 3));
        drop(g);
    }
    /* <(0 2)> on 3 points, L=(): t = id, G_M = G, orbits {0,2},{1} ordered by least point:
     * ids [0,1,0]. */
    {
        const uint32_t gen[3] = {2, 1, 0};
        canon_group *g = make(3, gen, 1, 100);
        uint32_t t[3], orb[3];
        CHECK(g->ops->tuple_min(g, NULL, 0, t, orb) == CANON_COMPLETE);
        CHECK(t[0] == 0 && t[1] == 1 && t[2] == 2);
        CHECK(orb[0] == 0 && orb[1] == 1 && orb[2] == 0);
        /* L=(0,1): (0 2) moves 0 so the least image is (0,1) with t = id; G_M trivial. */
        const uint32_t L[2] = {0, 1};
        CHECK(g->ops->tuple_min(g, L, 2, t, orb) == CANON_COMPLETE);
        CHECK(t[0] == 0 && t[1] == 1 && t[2] == 2);
        CHECK(orb[0] == 0 && orb[1] == 1 && orb[2] == 2);
        drop(g);
    }
    /* <(1 2)> on 3 points, L=(0): tie between id and (1 2); the least g is id. */
    {
        const uint32_t gen[3] = {0, 2, 1};
        canon_group *g = make(3, gen, 1, 100);
        uint32_t t[3], orb[3];
        const uint32_t L[1] = {0};
        CHECK(g->ops->tuple_min(g, L, 1, t, orb) == CANON_COMPLETE);
        CHECK(t[0] == 0 && t[1] == 1 && t[2] == 2);
        CHECK(orb[0] == 0 && orb[1] == 1 && orb[2] == 1);
        drop(g);
    }
    /* <(0 1)(2 3)>, L=(3): images 3 (id) and 2; t = [1,0,3,2]; M=(2), G_M trivial. */
    {
        const uint32_t gen[4] = {1, 0, 3, 2};
        canon_group *g = make(4, gen, 1, 100);
        CHECK(g->ops->order(g) == 2);
        uint32_t t[4], orb[4];
        const uint32_t L[1] = {3};
        CHECK(g->ops->tuple_min(g, L, 1, t, orb) == CANON_COMPLETE);
        CHECK(eq(t, gen, 4));
        CHECK(orb[0] == 0 && orb[1] == 1 && orb[2] == 2 && orb[3] == 3);
        CHECK(g->ops->tuple_min(g, NULL, 0, t, orb) == CANON_COMPLETE);
        CHECK(orb[0] == 0 && orb[1] == 0 && orb[2] == 1 && orb[3] == 1);
        drop(g);
    }
    /* canon_group_alloc establishes one reference; share/unshare pair through const. */
    {
        const uint32_t gen[2] = {1, 0};
        canon_group *g = make(2, gen, 1, 10);
        CHECK(atomic_load(&g->refs->count) == 1);
        CHECK(g->refs == &g->refs_storage && g->block == (void *)g);
        const canon_group *shared = g;
        canon_group_share(shared);
        CHECK(atomic_load(&g->refs->count) == 2);
        canon_group_unshare(shared);
        CHECK(atomic_load(&g->refs->count) == 1);
        drop(g);
    }
    /* Degree 0: the trivial group, one element. */
    {
        canon_group *g = make(0, NULL, 0, 1);
        CHECK(g->ops->order(g) == 1);
        CHECK(in(g, NULL));
        uint32_t dummy = 7;
        CHECK(g->ops->tuple_min(g, NULL, 0, &dummy, &dummy) == CANON_COMPLETE);
        CHECK(dummy == 7);
        drop(g);
        /* Two empty generators on degree 0 are still the trivial group. */
        g = make(0, NULL, 2, 1);
        CHECK(g->ops->order(g) == 1);
        drop(g);
    }
    /* Redundant and identity generators: the full element list of Sym(3) gives Sym(3). */
    {
        canon_status st;
        canon_group *s3 = sym(3, 100, &st);
        const uint32_t all[6 * 3] = {0, 1, 2, 0, 2, 1, 1, 0, 2, 1, 2, 0, 2, 0, 1, 2, 1, 0};
        canon_group *g = make(3, all, 6, 6);
        CHECK(g->ops->order(g) == 6);
        for (int i = 0; i < 6; ++i) {
            CHECK(in(s3, all + 3 * i));
            CHECK(in(g, all + 3 * i));
        }
        drop(g);
        drop(s3);
    }
    return check_finish("test_group_explicit");
}
