/* Unit tests for the Perm, Group(H) and labeling-coset payloads (slice S4, docs/slices/S4.md
 * 3.4, 4; spec 4.1, 7.4, 9.4).
 *
 *  - the four spec 7.4 payloads (expected hex lives here only, spec 20);
 *  - every T1 group against a brute-force evaluation of spec 9.4 over its element table
 *    (orbits and factorials; greedy least elements of H \ K by closure);
 *  - presentation independence: greedy generators, the full element list, random generating
 *    sets and random bases give identical bytes (T1 and random groups with n <= 7);
 *  - rule 1 versus rule 2: Sym(5) from two generators (rule 1), A4 and D4 (rule 2), and
 *    2^k <= |H| for every rule-2 payload;
 *  - the coset payload Group(H) || Perm(r0) against brute force. */
#include <stdlib.h>
#include <string.h>

#include "bsgs/chain.h"
#include "bsgs/verify.h"
#include "check.h"
#include "encoding/group_stream.h"
#include "perm/perm.h"
#include "t1_groups.h"

#define MAXN 8u

static void random_perm(uint32_t *p, uint32_t n)
{
    for (uint32_t v = 0; v < n; ++v) {
        p[v] = v;
    }
    for (uint32_t v = n; v > 1; --v) {
        uint32_t j = (uint32_t)(check_rng() % v), t = p[v - 1];
        p[v - 1] = p[j];
        p[j] = t;
    }
}

/* Group(H) of the chain built from gens, into buf (cleared first). */
static void group_bytes(uint32_t n, const uint32_t *gens, uint32_t count, canon_buf *buf,
                        canon_group_bytes_stats *stats)
{
    canon_bsgs h;
    CHECK(canon_bsgs_build_verified(&h, n, gens, count) == CANON_COMPLETE);
    canon_buf_truncate(buf, 0);
    CHECK(canon_group_bytes_write(buf, &h, stats) == CANON_COMPLETE);
    canon_bsgs_free(&h);
}

/* ---- spec 7.4 hand-checked payloads ---- */

static void golden(void)
{
    canon_buf b;
    canon_buf_init(&b);
    canon_group_bytes_stats st;
    /* "Group(1)=01 00000000" (degree independent, including n = 0, 1) */
    group_bytes(0, NULL, 0, &b, &st);
    CHECK(check_hex_is(b.data, b.len, "01 00000000") && st.rule == 1);
    group_bytes(1, NULL, 0, &b, &st);
    CHECK(check_hex_is(b.data, b.len, "01 00000000"));
    const uint32_t swap[2] = {1, 0};
    group_bytes(2, NULL, 0, &b, &st);
    CHECK(check_hex_is(b.data, b.len, "01 00000000"));
    /* "on degree two, Group(Sym(2))=01 00000001 00000002 00000000 00000001" */
    group_bytes(2, swap, 1, &b, &st);
    CHECK(check_hex_is(b.data, b.len, "01 00000001 00000002 00000000 00000001"));
    CHECK(st.rule == 1 && st.k == 1);
    /* "C3 generated by [1,2,0] ... Group(C3)=00 00000001 00000003 00000000 00000001 00000001
     * 00000002 00000002 00000000" */
    const uint32_t c3[3] = {1, 2, 0};
    group_bytes(3, c3, 1, &b, &st);
    CHECK(check_hex_is(b.data, b.len,
                       "00 00000001 00000003 00000000 00000001 00000001 00000002 00000002 "
                       "00000000"));
    CHECK(st.rule == 2 && st.k == 1);
    /* the inverse generator [2,0,1] gives the same group, hence the same bytes */
    const uint32_t c3inv[3] = {2, 0, 1};
    canon_buf b2;
    canon_buf_init(&b2);
    group_bytes(3, c3inv, 1, &b2, NULL);
    CHECK(b2.len == b.len && memcmp(b.data, b2.data, b.len) == 0);
    /* "H=1 and r=[1,0] give 01 00000000 00000002 00000000 00000001 00000001 00000000" */
    canon_bsgs one;
    CHECK(canon_bsgs_build_verified(&one, 2, NULL, 0) == CANON_COMPLETE);
    canon_buf_truncate(&b, 0);
    CHECK(canon_coset_bytes_write(&b, &one, swap, NULL) == CANON_COMPLETE);
    CHECK(check_hex_is(b.data, b.len,
                       "01 00000000 00000002 00000000 00000001 00000001 00000000"));
    canon_bsgs_free(&one);
    /* Perm of the identity is U32(0); a 3-cycle lists its support, source then target */
    const uint32_t id3[3] = {0, 1, 2};
    canon_buf_truncate(&b, 0);
    CHECK(canon_perm_bytes_write(&b, id3, 3) == CANON_COMPLETE);
    CHECK(check_hex_is(b.data, b.len, "00000000"));
    canon_buf_free(&b);
    canon_buf_free(&b2);
}

/* ---- brute force over T1 element tables ---- */

static void put_u32(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)(v >> 24);
    p[1] = (uint8_t)(v >> 16);
    p[2] = (uint8_t)(v >> 8);
    p[3] = (uint8_t)v;
}

/* spec 9.4 evaluated by brute force on a T1 group (bit mask over the lexicographically
 * numbered elements of Sym(n)); returns the length written to out. */
static size_t brute_group_bytes(const t1_sym *s, uint32_t mask, uint8_t *out, uint32_t *rule)
{
    const uint32_t n = s->n;
    uint32_t orbit_of[4], size[4] = {0, 0, 0, 0};
    for (uint32_t v = 0; v < n; ++v) {
        orbit_of[v] = v;
    }
    /* orbit of v = least point reachable; points are tiny, so close by repeated passes */
    for (int pass = 0; pass < 4; ++pass) {
        for (uint32_t e = 0; e < s->count; ++e) {
            if (mask >> e & 1u) {
                for (uint32_t v = 0; v < n; ++v) {
                    uint32_t w = s->elem[e][v], a = orbit_of[v], b = orbit_of[w];
                    uint32_t m = a < b ? a : b;
                    for (uint32_t u = 0; u < n; ++u) {
                        if (orbit_of[u] == a || orbit_of[u] == b) {
                            orbit_of[u] = m;
                        }
                    }
                }
            }
        }
    }
    uint32_t product = 1;
    for (uint32_t v = 0; v < n; ++v) {
        size[orbit_of[v]] += 1;
    }
    for (uint32_t v = 0; v < n; ++v) {
        for (uint32_t f = 2; f <= size[v]; ++f) {
            product *= f;
        }
    }
    size_t len = 0;
    if (product == t1_popcount(mask)) {
        *rule = 1;
        uint32_t k = 0;
        for (uint32_t v = 0; v < n; ++v) {
            k += size[v] > 1;
        }
        out[len++] = 1;
        put_u32(out + len, k);
        len += 4;
        for (uint32_t root = 0; root < n; ++root) {
            if (size[root] > 1) {
                put_u32(out + len, size[root]);
                len += 4;
                for (uint32_t v = 0; v < n; ++v) {
                    if (orbit_of[v] == root) {
                        put_u32(out + len, v);
                        len += 4;
                    }
                }
            }
        }
        return len;
    }
    *rule = 2;
    out[len++] = 0;
    size_t k_at = len;
    len += 4;
    uint32_t known = 1u, chosen = 0, k = 0;
    while (known != mask) {
        uint32_t e = 0;
        while (!((mask & ~known) >> e & 1u)) {
            ++e; /* least element of H \ K */
        }
        chosen |= 1u << e;
        known = t1_closure(s, chosen);
        ++k;
        uint32_t moved = 0;
        for (uint32_t v = 0; v < n; ++v) {
            moved += s->elem[e][v] != v;
        }
        put_u32(out + len, moved);
        len += 4;
        for (uint32_t v = 0; v < n; ++v) {
            if (s->elem[e][v] != v) {
                put_u32(out + len, v);
                put_u32(out + len + 4, s->elem[e][v]);
                len += 8;
            }
        }
    }
    put_u32(out + k_at, k);
    return len;
}

static void t1(void)
{
    uint32_t rules[3] = {0, 0, 0};
    for (uint32_t n = 0; n <= 4; ++n) {
        t1_sym s;
        t1_sym_init(&s, n);
        t1_group groups[T1_MAX_GROUPS];
        const uint32_t ng = t1_subgroups(&s, groups);
        for (uint32_t gi = 0; gi < ng; ++gi) {
            const t1_group *g = &groups[gi];
            uint8_t want[512];
            uint32_t rule = 0;
            const size_t want_len = brute_group_bytes(&s, g->mask, want, &rule);
            canon_buf b;
            canon_buf_init(&b);
            canon_group_bytes_stats st;
            group_bytes(n, g->gens, g->gen_count, &b, &st);
            CHECK(b.len == want_len && memcmp(b.data, want, want_len) == 0);
            CHECK(st.rule == rule);
            rules[rule] += 1;
            if (st.rule == 2) {
                CHECK((1u << st.k) <= g->order); /* spec 9.4: each step doubles |K| */
            }
            /* presentation independence: the full element list */
            uint32_t all[24 * 4], count = 0;
            for (uint32_t e = 0; e < s.count; ++e) {
                if (g->mask >> e & 1u) {
                    memcpy(all + count * n, s.elem[e], n * sizeof *all);
                    ++count;
                }
            }
            canon_buf other;
            canon_buf_init(&other);
            group_bytes(n, all, count, &other, NULL);
            CHECK(other.len == b.len && (b.len == 0 || memcmp(other.data, b.data, b.len) == 0));
            /* random generating sets: random members, reversed, until they generate */
            for (int trial = 0; trial < 4; ++trial) {
                uint32_t gens[24 * 4], gc = 0, mask = 1u;
                while (mask != g->mask && gc < 24) {
                    uint32_t e = (uint32_t)(check_rng() % s.count);
                    if (g->mask >> e & 1u) {
                        memcpy(gens + gc * n, s.elem[e], n * sizeof *gens);
                        ++gc;
                        uint32_t m = 0;
                        for (uint32_t i = 0; i < gc; ++i) {
                            for (uint32_t f = 0; f < s.count; ++f) {
                                if (n == 0 || memcmp(s.elem[f], gens + i * n, n * 4) == 0) {
                                    m |= 1u << f;
                                    break;
                                }
                            }
                        }
                        mask = t1_closure(&s, m);
                    }
                }
                group_bytes(n, gens, gc, &other, NULL);
                CHECK(other.len == b.len &&
                      (b.len == 0 || memcmp(other.data, b.data, b.len) == 0));
            }
            /* random bases: rebase to a random prefix (verified) */
            canon_bsgs h, rb;
            CHECK(canon_bsgs_build_verified(&h, n, g->gens, g->gen_count) == CANON_COMPLETE);
            uint32_t prefix[4];
            random_perm(prefix, n);
            const uint32_t plen = n > 0 ? (uint32_t)(check_rng() % (n + 1u)) : 0;
            CHECK(canon_bsgs_rebase(&h, 0, prefix, plen, true, &rb) == CANON_COMPLETE);
            canon_buf_truncate(&other, 0);
            CHECK(canon_group_bytes_write(&other, &rb, NULL) == CANON_COMPLETE);
            CHECK(other.len == b.len && (b.len == 0 || memcmp(other.data, b.data, b.len) == 0));
            /* the coset payload against brute force: least of H r over every r */
            for (uint32_t ri = 0; ri < s.count; ++ri) {
                const uint32_t *r = s.elem[ri];
                uint32_t least = UINT32_MAX;
                for (uint32_t e = 0; e < s.count; ++e) {
                    if (g->mask >> e & 1u) {
                        const uint32_t idx = s.mul[e][ri]; /* elem[e] r, elem[e] first */
                        least = idx < least ? idx : least;
                    }
                }
                canon_buf_truncate(&other, 0);
                CHECK(canon_coset_bytes_write(&other, &rb, r, NULL) == CANON_COMPLETE);
                canon_buf perm;
                canon_buf_init(&perm);
                CHECK(canon_perm_bytes_write(&perm, s.elem[least], n) == CANON_COMPLETE);
                CHECK(other.len == b.len + perm.len && memcmp(other.data, b.data, b.len) == 0 &&
                      memcmp(other.data + b.len, perm.data, perm.len) == 0);
                canon_buf_free(&perm);
            }
            canon_bsgs_free(&h);
            canon_bsgs_free(&rb);
            canon_buf_free(&other);
            canon_buf_free(&b);
        }
    }
    printf("T1 Group(H): %u by rule 1, %u by rule 2\n", rules[1], rules[2]);
    CHECK(rules[1] > 0 && rules[2] > 0 && rules[1] + rules[2] == 40);
}

/* ---- named groups ---- */

static void named(void)
{
    canon_buf b;
    canon_buf_init(&b);
    canon_group_bytes_stats st;
    /* Sym(5) from (0 1) and the 5-cycle: rule 1, one block {0..4} */
    const uint32_t s5[10] = {1, 0, 2, 3, 4, 1, 2, 3, 4, 0};
    group_bytes(5, s5, 2, &b, &st);
    CHECK(st.rule == 1 && st.k == 1);
    CHECK(check_hex_is(b.data, b.len,
                       "01 00000001 00000005 00000000 00000001 00000002 00000003 00000004"));
    /* A4 from (0 1 2) and (1 2 3): orbit {0,1,2,3}, 4! = 24 != 12, rule 2.  Least nonidentity
     * element: [0,2,3,1]; <[0,2,3,1]> has order 3; the least element outside it is [1,0,3,2],
     * and the two generate A4 (order 12 = 3 * 4).  So k = 2. */
    const uint32_t a4[8] = {1, 2, 0, 3, 0, 2, 3, 1};
    group_bytes(4, a4, 2, &b, &st);
    CHECK(st.rule == 2 && st.k == 2 && (1u << st.k) <= 12u);
    CHECK(check_hex_is(b.data, b.len,
                       "00 00000002 "
                       "00000003 00000001 00000002 00000002 00000003 00000003 00000001 "
                       "00000004 00000000 00000001 00000001 00000000 00000002 00000003 "
                       "00000003 00000002"));
    /* D4 on the square 0-1-2-3: rotation [1,2,3,0] and reflection [0,3,2,1] (order 8, one
     * orbit of size 4, 24 != 8: rule 2).  Elements in lexicographic order: [0,1,2,3],
     * [0,3,2,1], [1,0,3,2], [1,2,3,0], ...  g1 = [0,3,2,1] (order 2); the least outside
     * <g1> is [1,0,3,2], and <g1, [1,0,3,2]> = D4 (the product [0,3,2,1][1,0,3,2] =
     * [1,2,3,0] has order 4).  So k = 2. */
    const uint32_t d4[8] = {1, 2, 3, 0, 0, 3, 2, 1};
    group_bytes(4, d4, 2, &b, &st);
    CHECK(st.rule == 2 && st.k == 2);
    CHECK(check_hex_is(b.data, b.len,
                       "00 00000002 "
                       "00000002 00000001 00000003 00000003 00000001 "
                       "00000004 00000000 00000001 00000001 00000000 00000002 00000003 "
                       "00000003 00000002"));
    canon_buf_free(&b);
}

/* ---- random groups: presentation independence ---- */

static void t2(void)
{
    uint32_t rule2 = 0;
    for (uint32_t trial = 0; trial < 60; ++trial) {
        const uint32_t n = 2u + (uint32_t)(check_rng() % 6u); /* 2..7 */
        uint32_t gens[3 * MAXN];
        const uint32_t count = 1u + (uint32_t)(check_rng() % 3u);
        for (uint32_t i = 0; i < count; ++i) {
            if (check_rng() % 2u == 0) {
                random_perm(gens + i * n, n);
            } else {
                /* a random transposition or 3-cycle keeps many groups small */
                uint32_t *p = gens + i * n;
                for (uint32_t v = 0; v < n; ++v) {
                    p[v] = v;
                }
                uint32_t a = (uint32_t)(check_rng() % n), b = (uint32_t)(check_rng() % n);
                p[a] = b;
                p[b] = a;
            }
        }
        canon_bsgs h;
        CHECK(canon_bsgs_build_verified(&h, n, gens, count) == CANON_COMPLETE);
        canon_buf b, other;
        canon_buf_init(&b);
        canon_buf_init(&other);
        canon_group_bytes_stats st;
        CHECK(canon_group_bytes_write(&b, &h, &st) == CANON_COMPLETE);
        if (st.rule == 2) {
            ++rule2;
            CHECK(st.k < 64 && ((uint64_t)1 << st.k) <= h.order);
        }
        /* another presentation: the strong generators plus random products of the inputs */
        uint32_t more[12 * MAXN], mc = 0;
        for (uint32_t i = 0; i < count; ++i) {
            canon_perm_compose(gens + i * n, gens + ((i + 1) % count) * n, more + mc * n, n);
            ++mc;
            canon_perm_inverse(gens + i * n, more + mc * n, n);
            ++mc;
        }
        for (uint32_t i = 0; i < h.gens.count && mc < 12; ++i) {
            memcpy(more + mc * n, canon_perm_table_row(&h.gens, i), n * sizeof *more);
            ++mc;
        }
        canon_bsgs h2;
        CHECK(canon_bsgs_build_verified(&h2, n, more, mc) == CANON_COMPLETE);
        if (h2.order == h.order) { /* the same group (h2 <= h, equal order) */
            CHECK(canon_group_bytes_write(&other, &h2, NULL) == CANON_COMPLETE);
            CHECK(other.len == b.len && memcmp(other.data, b.data, b.len) == 0);
        }
        canon_bsgs_free(&h2);
        /* a random base */
        uint32_t prefix[MAXN];
        random_perm(prefix, n);
        canon_bsgs rb;
        CHECK(canon_bsgs_rebase(&h, 0, prefix, n, true, &rb) == CANON_COMPLETE);
        canon_buf_truncate(&other, 0);
        CHECK(canon_group_bytes_write(&other, &rb, NULL) == CANON_COMPLETE);
        CHECK(other.len == b.len && memcmp(other.data, b.data, b.len) == 0);
        canon_bsgs_free(&rb);
        canon_bsgs_free(&h);
        canon_buf_free(&b);
        canon_buf_free(&other);
    }
    printf("T2 Group(H): 60 groups, %u by rule 2\n", rule2);
}

static void bound(void)
{
    uint64_t b = 0;
    CHECK(canon_group_bytes_bound(2, 2, false, &b) && b == 5u + 1u * 20u); /* rule 2 term */
    CHECK(canon_group_bytes_bound(4, 12, true, &b) && b == 5u + 3u * 36u + 36u);
    CHECK(canon_group_bytes_bound(0, 1, false, &b) && b == 5u);
}

int main(void)
{
    golden();
    t1();
    named();
    t2();
    bound();
    return check_finish("test_group_stream");
}
