/*
 * Internal header: the verified automorphism subgroup A_known and the prefix stabilisers used
 * for orbit pruning of the P1 canonical-image tree (spec 7.3; slice S7 step 1,
 * docs/slices/S7.md 3.1, 3.2; the rule and its proof are in docs/pruning-rules.md).
 *
 * spec 7.3: "Known automorphisms form a verified subgroup A_known <= A.  At each node intersect
 * with the stabiliser of its constraints before sibling pruning. ... Verify implicit
 * automorphisms by exact membership and object equality before publication."  spec 14.3 R2:
 * only exactly verified automorphisms may contribute.
 *
 * A_known is a verified stabiliser chain (canon_bsgs_build_verified from zero generators,
 * grown by canon_bsgs_insert_verified) of the group generated by the automorphisms that passed
 * canon_symmetry_insert.  S7 step 1 has one source, (i) of the brief: the input generators of
 * G that fix x (canon_symmetry_from_inputs).  Source (ii), implicit automorphisms from equal
 * leaf keys, is slice S7b.
 *
 * Prefix stabilisers.  For a tree node with prefix (a_1, ..., a_d), H_d is the pointwise
 * stabiliser of a_1..a_d in A_known (H_0 = A_known).  H_{d+1} is the stabiliser of a_{d+1} in
 * H_d, computed by canon_bsgs_rebase without verification (S3: transient chains of a descent)
 * from the strong generators of H_d with base prefix (a_{d+1}); its level 1 generates H_{d+1}.
 * One rebase per explored child whose parent's H is nontrivial; none at all once H is trivial.
 *
 * Convention (spec 3): permutations are image arrays p[v] = v^p, products act left to right,
 * (pq)[v] = q[p[v]]; x^p is canon_root_act_into(x, p).
 */
#ifndef CANON_SRC_SYMMETRY_SYMMETRY_H
#define CANON_SRC_SYMMETRY_SYMMETRY_H

#include <stdbool.h>
#include <stdint.h>

#include "bsgs/chain.h"
#include "bsgs/group.h"
#include "canon/canon.h"
#include "object/object.h"
#include "perm/perm.h"

/* Operation counts (no timings; read by tests and the S7 notes). */
typedef struct canon_symmetry_stats {
    uint64_t considered;  /* candidates offered to canon_symmetry_insert */
    uint64_t rejected;    /* refused by insert: not a bijection, not in G, or x^p != x */
    uint64_t not_fixing;  /* input generators skipped by from_inputs because x^g != x */
    uint64_t inserted;    /* verified insertions that enlarged A_known (|A_known| at least
                             doubles each time) */
    uint64_t rebases;     /* canon_bsgs_rebase calls made by canon_symmetry_descend */
    uint64_t orbit_calls; /* canon_symmetry_orbit_reps calls */
} canon_symmetry_stats;

/* One prefix-stabiliser slot: for d >= 1, `chain` was rebased with base prefix (a_d) from the
 * generators of H_{d-1}, so its level 1 generates H_d; slot 0's chain is unused (H_0 is
 * A_known's own chain at level 0).  `trivial` is H_d = 1. */
typedef struct canon_symmetry_slot {
    canon_bsgs chain;
    bool trivial;
} canon_symmetry_slot;

typedef struct canon_symmetry {
    uint32_t n;                 /* degree of the current A_known */
    canon_bsgs chain;           /* verified chain of A_known */
    canon_perm_table gens;      /* the automorphisms inserted, in insertion order (A_known =
                                   <gens>; insert_verified's generator list) */
    canon_symmetry_slot *slots; /* slots[d], d < slot_count; grow-only */
    uint32_t slot_count;        /* initialised slots */
    uint32_t slot_cap;          /* allocated slots */
    uint32_t cap;               /* degree the scratch arrays are allocated for (grow-only) */
    uint32_t *work;             /* cap words: sift scratch */
    uint32_t *orbit_id;         /* cap words: orbit ids of the last orbit computation */
    uint32_t *rep;              /* cap words: least member per orbit id */
    uint8_t *in_cell;           /* cap bytes: membership of the target cell (cleared after use) */
    canon_symmetry_stats stats;
} canon_symmetry;

/* Zero state, no allocation. */
void canon_symmetry_init(canon_symmetry *a);
/* Release all storage; valid on an initialised or failed state. */
void canon_symmetry_free(canon_symmetry *a);

/* A_known := 1 on n points (a verified chain with no generators), stats zeroed, slot 0
 * trivial.  Storage is reused.  CANON_RESOURCE_LIMIT / CANON_CAPACITY_LIMIT on allocation
 * failure (then A_known is unusable until the next successful reset). */
canon_status canon_symmetry_reset(canon_symmetry *a, uint32_t n);

/* spec 7.3 "Verify ... by exact membership and object equality before publication", spec 14.3
 * R2: insert p into A_known only after checking that p is a bijection of {0..n-1}
 * (canon_perm_check), that p is in G (g->ops->contains) and that x^p = x (canon_root_act_into
 * into *img, then canon_root_equal; the image is cleared afterwards, so it borrows nothing from
 * x on return).  Then canon_bsgs_insert_verified: *inserted is true iff p was not already in
 * A_known (identities and members are not inserted).  A failed check is CANON_INVALID_INPUT
 * with A_known unchanged (stats.rejected += 1); allocation failure leaves A_known unchanged.
 * g and x have degree a->n.  The prefix slots are not updated: insert before descending. */
canon_status canon_symmetry_insert(canon_symmetry *a, const canon_group *g, const canon_root *x,
                                   canon_root_image *img, const uint32_t *p, bool *inserted);

/* Source (i) of docs/slices/S7.md 3.1: every input generator of g
 * (canon_group_input_generators, input order, identities and repeats included) that fixes x
 * goes through the checks of canon_symmetry_insert; one that does not fix x is skipped
 * (stats.not_fixing += 1), not an error.  A generator that fails the bijection or membership
 * check is CANON_INTERNAL_ERROR (the handle's own generators are bijections in G).  No
 * recorded generators: A_known stays trivial.  Call after canon_symmetry_reset(a, x->n). */
canon_status canon_symmetry_from_inputs(canon_symmetry *a, const canon_group *g,
                                        const canon_root *x, canon_root_image *img);

/* H_depth = 1?  depth 0 asks about A_known itself; depth d >= 1 is valid only after
 * canon_symmetry_descend(a, d - 1, ...) on the current path. */
bool canon_symmetry_trivial_at(const canon_symmetry *a, uint32_t depth);

/* spec 7.3 "At each node intersect with the stabiliser of its constraints": H_{depth+1} = the
 * stabiliser of `atom` in H_depth (H_depth must be valid, see trivial_at), stored in slot
 * depth + 1 (replacing what a sibling left there).  A trivial H_depth gives a trivial
 * H_{depth+1} without a rebase.  CANON_INVALID_INPUT for atom >= n; allocation failure as
 * canon_bsgs_rebase. */
canon_status canon_symmetry_descend(canon_symmetry *a, uint32_t depth, uint32_t atom);

/* The child selection of docs/pruning-rules.md: members[0..len) are the atoms of the node's
 * target cell C (distinct, < n).  Writes to reps, in member order, the members that are the
 * NUMERICALLY least member of their H_depth-orbit, and *count = how many (one per orbit).
 * Orbits come from union-find over H_depth's generators (canon_bsgs_orbit_ids).  Soundness
 * guard: every generator of H_depth must map C into itself (the lemma's C_S^a = C_S); a
 * violation is CANON_INTERNAL_ERROR (never observed: it would mean A_known holds a
 * non-automorphism or H_depth moves the prefix).  reps has room for len entries and may not
 * alias members. */
canon_status canon_symmetry_orbit_reps(canon_symmetry *a, uint32_t depth, const uint32_t *members,
                                       uint32_t len, uint32_t *reps, uint32_t *count);

/* The chain and level whose generators generate H_depth (A_known's chain at level 0 for depth
 * 0, else slot depth's chain at level 1); for tests. */
void canon_symmetry_view(const canon_symmetry *a, uint32_t depth, const canon_bsgs **chain,
                         uint32_t *level);

#endif /* CANON_SRC_SYMMETRY_SYMMETRY_H */
