/*
 * Internal header: the disjoint coset enumerator of spec 8.1 and the constrained least-element
 * descent of spec 9.4 (slice S4, docs/slices/S4.md 3.1, 3.2; detailed plan 2.4, WP2.6).
 *
 * Convention (spec 3): permutations are dense image arrays p[v] = v^p; products act left to
 * right, (pq)[v] = q[p[v]].  A coset J r is {j r : j in J}: j acts first, then r, so the image
 * of a point v under the coset is (v^J)^r = {r[j[v]] : j in J}.
 *
 * A subgroup is given as the suffix of a stabiliser chain (src/bsgs/chain.h) from `level`: the
 * group K_level generated by that level's strong generators.  Every chain built here for a
 * descent step is transient and is not verified (S3 review item 2); chains that are answers
 * are built by canon_bsgs_build_verified.
 */
#ifndef CANON_SRC_COSET_COSET_H
#define CANON_SRC_COSET_COSET_H

#include <stdbool.h>
#include <stdint.h>

#include "bsgs/chain.h"
#include "canon/canon.h"

/* A point constraint v -> c: only elements g with g[v] = c are admitted (spec 9.4 "successive
 * point constraints"). */
typedef struct canon_coset_constraint {
    uint32_t point, image;
} canon_coset_constraint;

/* Operation counts of the descents and the enumerator (spec 8.3: "Deterministic witness
 * minimisation adds a distinct search or coset-minimum cost and must appear in metrics"; spec
 * 9.2 ledgers).  No timings. */
typedef struct canon_coset_stats {
    uint64_t descents; /* calls of the least-element descents */
    uint64_t rebuilds; /* transient chain rebuilds (one per base change, spec 9.2) */
} canon_coset_stats;

/* spec 9.4 ("choose its least image-array element r0 by successive point constraints"), 8.1
 * (t_b): the lexicographically least image array in the coset J r, J = K_level of `c`, among
 * the elements g with g[v_i] = c_i for the k constraints (k may be 0; `cons` may then be NULL).
 * `r` is a permutation of {0..n-1}, or NULL for the identity.  On CANON_COMPLETE, *found tells
 * whether an element satisfies the constraints, and if so `out` (n entries, not aliasing r)
 * holds the least one.  CANON_INVALID_INPUT for level > depth or a constraint point or image
 * >= n; CANON_RESOURCE_LIMIT / CANON_CAPACITY_LIMIT when scratch or a transient chain cannot
 * be allocated.  `stats` may be NULL. */
canon_status canon_coset_least(const canon_bsgs *c, uint32_t level, const uint32_t *r,
                               const canon_coset_constraint *cons, uint32_t k, uint32_t *out,
                               bool *found, canon_coset_stats *stats);

/* spec 9.4 rule 2: "repeatedly choose the lexicographically least image-array g in H \ K".
 * H is the whole group of chain `h`, K the group of chain `k` (same degree), K <= H.  On
 * CANON_COMPLETE *found is false iff K = H; otherwise `out` holds the least element of H \ K.
 * The descent discards a branch C = J r exactly when C is contained in K, tested as "r in K and
 * J <= K" (spec 9.4).  Allocation failure as canon_coset_least; CANON_INVALID_INPUT for a
 * degree mismatch. */
canon_status canon_coset_least_outside(const canon_bsgs *h, const canon_bsgs *k, uint32_t *out,
                                       bool *found, canon_coset_stats *stats);

/* ---- the spec 8.1 enumerator ---- */

/* spec 8.2 consume(r): r (n entries) is valid only during the call.  Set *stop to end the
 * enumeration successfully (transporter one: "stop successfully on one hit").  A status other
 * than CANON_COMPLETE abandons the enumeration with that status. */
typedef canon_status (*canon_coset_consume_fn)(void *user, const uint32_t *r, bool *stop);

/* Cancellation poll, called once per visited node before it is counted; true cancels the
 * enumeration with CANON_CANCELLED (spec 11.1: a cancellation policy, not semantic capacity). */
typedef bool (*canon_coset_poll_fn)(void *user);

/* The consumer and the counters of one or more enumerations.  The counters accumulate across
 * enumerations sharing a visitor (the transporter-coset objective runs two). */
typedef struct canon_coset_visitor {
    canon_coset_consume_fn consume;
    canon_coset_poll_fn cancelled; /* may be NULL */
    void *user;
    uint64_t quota;  /* spec 11.1 logical work quota: visit calls admitted in total */
    uint64_t nodes;  /* visit calls so far (each counts once, leaves included) */
    uint64_t leaves; /* consume calls */
    bool stopped;    /* the consumer asked to stop */
    canon_coset_stats stats;
} canon_coset_visitor;

/* Start a visitor: consumer, poll, quota; counters zero. */
void canon_coset_visitor_init(canon_coset_visitor *v, canon_coset_consume_fn consume,
                              canon_coset_poll_fn cancelled, void *user, uint64_t quota);

/* The node-entry rule shared by every implementation of the spec 8.1 traversal (the chain
 * enumerator below and the explicit backend's oracle): poll for cancellation
 * (CANON_CANCELLED), then refuse the visit with CANON_CAPACITY_LIMIT when `quota` visits were
 * already made (spec 11.1: "A logical work quota ... counts the fixed reference traversal"),
 * else count it.  Because the traversal is fixed, CAPACITY_LIMIT is a function of the input
 * and the descriptor. */
canon_status canon_coset_visit_enter(canon_coset_visitor *v);

/* spec 8.1: visit(G, id) over the group of chain `c` (all of it, level 0), with zero pruning:
 *     visit(H, r): if H = 1 consume(r); else a = least point moved by H; for b in sorted a^H:
 *                  t_b = least element of H with a^t_b = b; visit(H_a, t_b r).
 * Every element of G is consumed exactly once ("Singleton leaves partition G with |G|
 * leaves").  Returns CANON_COMPLETE when the traversal was exhausted or the consumer stopped
 * it (v->stopped), CANON_CAPACITY_LIMIT when the quota is exceeded, CANON_CANCELLED, or a
 * consumer or allocation status. */
canon_status canon_coset_enumerate(const canon_bsgs *c, canon_coset_visitor *v);

/* The least point moved by K_level of c (CANON_BSGS_NONE if K_level is trivial). */
uint32_t canon_coset_least_moved(const canon_bsgs *c, uint32_t level);

#endif /* CANON_SRC_COSET_COSET_H */
